"../RTL/Bias_Adding_Unit/bias_adder.sv"
"../RTL/Bias_Adding_Unit/Bias_Adding_Unit.sv"
"../RTL/Buffers/acc_buffer.sv"
"../RTL/Buffers/bias_buffer.sv"
"../RTL/Buffers/pbias_buffer.sv"
"../RTL/Buffers/pingpong_buffer.sv"
"../RTL/Buffers/preq_buffer.sv"
"../RTL/Buffers/relu_buffer.sv"
"../RTL/Buffers/scale_reg.sv"
"../RTL/Clock_Gating_Cell/Clk_Gating_Cell.sv"
"../RTL/Control Unit/CU.SV"
"../RTL/MUX/mux2x1.sv"
"../RTL/MUX/mux4x1.sv"
"../RTL/Npu_apb_decoder.sv"
"../RTL/npu_system_top.sv"
"../RTL/npu_top.sv"
"../RTL/Pooling Unit/pooling_unit.sv"
"../RTL/ReLU/ReLU.sv"
"../RTL/ReLU/relu_unit.sv"
"../RTL/Req/Req.sv"
"../RTL/SRAM/0.25Kb/RAM64x32_1RW1R.sv"
"../RTL/SRAM/0.5Kb/RAM128x32_1RW1R.sv"
"../RTL/SRAM/1Kb/RAM256x32_1RW1R_.sv"
"../RTL/SRAM/1Kb/ram_1kb_dp.v"
"../RTL/SRAM/instr_mem/32x32/imem_32x32.v"
"../RTL/SRAM/instr_mem/RAM32_.sv"
"../RTL/Store_Engine/store_engine.sv"
"../RTL/Synchronous FIFO/act_sync_fifo.sv"
"../RTL/Synchronous FIFO/sync_fifo.sv"
"../RTL/Synchronous FIFO/weight_sync_fifo.sv"
"../RTL/Systolic Array/PE.sv"
"../RTL/Systolic Array/SA_CU.sv"
"../RTL/Systolic Array/SA_NxN.sv"
"../RTL/Systolic Array/SA_NxN_top.sv"
"../RTL/Systolic Array/TRSDL.sv"
"../RTL/Systolic Array/TRSRL.sv"
"../RTL/UART APB/apb_master.v"
"../RTL/UART APB/apb_splitter.v"
"../RTL/UART APB/baud_gen.v"
"../RTL/UART APB/cmd_parser.v"
"../RTL/UART APB/resp_builder.v"
"../RTL/UART APB/uart_apb_master.v"
"../RTL/UART APB/uart_apb_sys.v"
"../RTL/UART APB/uart_rx.v"
"../RTL/UART APB/uart_tx.v"
